version: "3.9"

services:
  skimmer-server:
    build: ./server
    container_name: skimmer-server
    ports:
      - "3000:3000"

  web:
      image: nginx:alpine
      container_name: skimmer-web
      ports:
        - "8080:80"
      volumes:
        - ./public:/usr/share/nginx/html:ro
        - ./nginx:/etc/nginx/conf.d:ro

